"""
renderer.py — Generate print-ready HTML and XML for ARIA form submissions.
"""
from datetime import datetime
from forms.schemas import OccurrenceReportSchema, TeddyBearSchema, ShiftChangeRequestSchema


def render_occurrence_report_html(data: OccurrenceReportSchema) -> str:
    optional_rows = ""
    if data.call_number:
        optional_rows += f"<tr><td>Call Number</td><td>{data.call_number}</td></tr>"
    if data.action_taken:
        optional_rows += f"<tr><td>Action Taken</td><td>{data.action_taken}</td></tr>"
    if data.other_services_involved:
        optional_rows += f"<tr><td>Other Services</td><td>{data.other_services_involved}</td></tr>"
    if data.suggested_resolution:
        optional_rows += f"<tr><td>Suggested Resolution</td><td>{data.suggested_resolution}</td></tr>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>EMS Occurrence Report — {data.date}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 0; padding: 0; background: #fff; color: #1a1a2e; }}
    .header {{ background: #1a2a4a; color: #fff; padding: 24px 32px; }}
    .header h1 {{ margin: 0; font-size: 22px; letter-spacing: 1px; }}
    .header p {{ margin: 4px 0 0; font-size: 13px; color: #a0b4cc; }}
    .body {{ padding: 32px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
    th {{ background: #e8edf5; text-align: left; padding: 10px 14px; font-size: 12px;
          text-transform: uppercase; letter-spacing: 0.5px; color: #4a5568; }}
    td {{ padding: 10px 14px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }}
    td:first-child {{ font-weight: 600; color: #2d3748; width: 35%; }}
    .section-label {{ font-size: 13px; font-weight: 700; color: #1a2a4a;
                      text-transform: uppercase; margin: 24px 0 8px; letter-spacing: 1px; }}
    .footer {{ padding: 16px 32px; font-size: 11px; color: #a0aec0; border-top: 1px solid #e2e8f0; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>🚑 EMS Occurrence Report</h1>
    <p>Generated by ARIA — Ambulance Response Intelligence Assistant</p>
  </div>
  <div class="body">
    <div class="section-label">Report Details</div>
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Date</td><td>{data.date}</td></tr>
      <tr><td>Time</td><td>{data.time}</td></tr>
      <tr><td>Occurrence Type</td><td>{data.occurrence_type.value}</td></tr>
      <tr><td>Unit / Vehicle Number</td><td>{data.vehicle_number}</td></tr>
    </table>

    <div class="section-label">Reporter Information</div>
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Report Creator</td><td>{data.report_creator}</td></tr>
      <tr><td>Badge Number</td><td>{data.badge_number}</td></tr>
      <tr><td>Creator Details</td><td>{data.creator_details}</td></tr>
      <tr><td>Requested By</td><td>{data.requested_by}</td></tr>
    </table>

    <div class="section-label">Incident Description</div>
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Brief Description</td><td>{data.brief_description}</td></tr>
      <tr><td>Observation / Detail</td><td>{data.observation}</td></tr>
      {optional_rows}
    </table>
  </div>
  <div class="footer">
    Submitted via ARIA EMS Assistant &bull; {datetime.now().strftime("%Y-%m-%d %H:%M")} &bull; Confidential
  </div>
</body>
</html>"""


def render_teddy_bear_html(data: TeddyBearSchema) -> str:
    second_medic_block = ""
    if data.second_medic_first:
        second_medic_block = f"""
      <tr><td>Second Medic</td><td>{data.second_medic_first} {data.second_medic_last}</td></tr>
      <tr><td>Second Medic Number</td><td>{data.second_medic_number or "—"}</td></tr>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Teddy Bear Comfort Program — {data.date_time[:10]}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 0; padding: 0; background: #fff; color: #1a1a2e; }}
    .header {{ background: #1565c0; color: #fff; padding: 24px 32px; }}
    .header h1 {{ margin: 0; font-size: 22px; }}
    .header p {{ margin: 4px 0 0; font-size: 13px; color: #90caf9; }}
    .bear-icon {{ font-size: 36px; float: right; margin-top: -8px; }}
    .body {{ padding: 32px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
    th {{ background: #e3f2fd; text-align: left; padding: 10px 14px; font-size: 12px;
          text-transform: uppercase; letter-spacing: 0.5px; color: #1565c0; }}
    td {{ padding: 10px 14px; border-bottom: 1px solid #e3f2fd; font-size: 14px; }}
    td:first-child {{ font-weight: 600; color: #1565c0; width: 35%; }}
    .section-label {{ font-size: 13px; font-weight: 700; color: #1565c0;
                      text-transform: uppercase; margin: 24px 0 8px; letter-spacing: 1px; }}
    .footer {{ padding: 16px 32px; font-size: 11px; color: #90caf9;
               border-top: 1px solid #e3f2fd; background: #f8fbff; }}
  </style>
</head>
<body>
  <div class="header">
    <span class="bear-icon">🧸</span>
    <h1>Teddy Bear Comfort Program</h1>
    <p>Compassionate Care — EMS Community Program</p>
  </div>
  <div class="body">
    <div class="section-label">Submission Details</div>
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Date / Time</td><td>{data.date_time}</td></tr>
      <tr><td>Primary Medic</td><td>{data.primary_medic_first} {data.primary_medic_last}</td></tr>
      <tr><td>Primary Medic Number</td><td>{data.primary_medic_number}</td></tr>
      {second_medic_block}
    </table>

    <div class="section-label">Recipient Information</div>
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Approximate Age</td><td>{data.recipient_age}</td></tr>
      <tr><td>Gender</td><td>{data.recipient_gender.value}</td></tr>
      <tr><td>Recipient Type</td><td>{data.recipient_type.value}</td></tr>
    </table>
  </div>
  <div class="footer">
    Submitted via ARIA EMS Assistant &bull; {datetime.now().strftime("%Y-%m-%d %H:%M")} &bull;
    Teddy Bear Comfort Program
  </div>
</body>
</html>"""


def render_teddy_bear_xml(data: TeddyBearSchema, timestamp: str) -> str:
    second_medic_xml = ""
    if data.second_medic_first:
        second_medic_xml = f"""
  <secondMedic optional="true">
    <firstName>{data.second_medic_first}</firstName>
    <lastName>{data.second_medic_last or ""}</lastName>
    <medicNumber>{data.second_medic_number or ""}</medicNumber>
  </secondMedic>"""
    else:
        second_medic_xml = '\n  <secondMedic optional="true"/>'

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<TeddyBearComfortReport>
  <formId>TB-{timestamp}</formId>
  <submitted>{data.date_time}</submitted>
  <primaryMedic>
    <firstName>{data.primary_medic_first}</firstName>
    <lastName>{data.primary_medic_last}</lastName>
    <medicNumber>{data.primary_medic_number}</medicNumber>
  </primaryMedic>{second_medic_xml}
  <recipient>
    <age>{data.recipient_age}</age>
    <gender>{data.recipient_gender.value}</gender>
    <recipientType>{data.recipient_type.value}</recipientType>
  </recipient>
</TeddyBearComfortReport>"""


def render_shift_change_html(data: ShiftChangeRequestSchema) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Shift Change Request — {data.medic_number}</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 0; padding: 0; background: #fff; color: #1a1a2e; }}
    .header {{ background: #2d3748; color: #fff; padding: 24px 32px; }}
    .header h1 {{ margin: 0; font-size: 22px; }}
    .body {{ padding: 32px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
    th {{ background: #edf2f7; text-align: left; padding: 10px 14px; font-size: 12px;
          text-transform: uppercase; letter-spacing: 0.5px; color: #4a5568; }}
    td {{ padding: 10px 14px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }}
    td:first-child {{ font-weight: 600; color: #2d3748; width: 35%; }}
  </style>
</head>
<body>
  <div class="header">
    <h1>Shift Change Request</h1>
  </div>
  <div class="body">
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>Name</td><td>{data.first_name} {data.last_name}</td></tr>
      <tr><td>Medic Number</td><td>{data.medic_number}</td></tr>
      <tr><td>Shift Date</td><td>{data.shift_date}</td></tr>
      <tr><td>Shift Start</td><td>{data.shift_start}</td></tr>
      <tr><td>Shift End</td><td>{data.shift_end}</td></tr>
      <tr><td>Requested Action</td><td>{data.requested_action.value}</td></tr>
      <tr><td>Notes</td><td>{data.notes or "—"}</td></tr>
    </table>
  </div>
</body>
</html>"""
